app/api/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter

from api import views


app_name = 'api'

router = DefaultRouter()

router.register('clients', views.ClientViewSet, 'clients')
router.register('organizations', views.OrganizationViewSet, 'organizations')
router.register('bills', views.BillViewSet, 'bills')

urlpatterns = [
    path('', views.index, name='main'),
    path('upload-files/', views.upload_files, name='upload_files'),
    *router.urls,
]

app/clients/urls.py
from django.urls import path

from clients import views


app_name = 'clients'

urlpatterns = [
    path('', views.index, name='main'),
    path('upload-files/', views.upload_files, name='upload_files'),
    path('clients/', views.ClientView.as_view(), name='clients_list'),
    path('organizations/', views.OrganizationView.as_view(), name='organizations_list'),
    path('bills/', views.BillsView.as_view(), name='bills_list'),
    path('clients/<slug:slug>/', views.ClientDetailViews.as_view(), name='clients_detailed')
]

app/src/urls.py
from django.contrib import admin
from django.urls import path, include

from src import views


urlpatterns = [
    path('', views.index, name='main'),
    path('admin/', admin.site.urls),
    path('clients/', include('clients.urls'), name='clients'),
    path('api/', include('api.urls'), name='api'),
]

app/api/models.py
from django.db import models

# Create your models here.

app/clients/models.py
from django.db import models


class Client(models.Model):
    name = models.CharField(verbose_name='Имя клиента', max_length=64, unique=True)


class Organization(models.Model):
    name = models.CharField(verbose_name='Название организации', max_length=64)
    client = models.ForeignKey(Client, verbose_name='Клиент', on_delete=models.CASCADE)


class Bill(models.Model):
    organization = models.OneToOneField(Organization, verbose_name='Организация', on_delete=models.CASCADE)
    unique_id = models.IntegerField(verbose_name='Уникальный номер', unique=True)
    _sum = models.IntegerField(verbose_name='Сумма', name='sum')
    date = models.DateTimeField(verbose_name='Дата')

app/clients/forms.py
from django import forms

from clients import validators


class UploadForm(forms.Form):
    bills = forms.FileField(required=False,
                            validators=
                            [
                                validators.validate_file_format_bills,
                                validators.validate_bills,
                            ])
    client_org = forms.FileField(required=False,
                                 validators=
                                 [
                                     validators.validate_file_format_client_org,
                                     validators.validate_client_org,
                                 ])

    def clean(self):
        cleaned_data = super(UploadForm, self).clean()
        bills = cleaned_data.get('bills')
        client_org = cleaned_data.get('client_org')

        if bills is None and client_org is None:
            raise forms.ValidationError(
                [
                    {
                        'bills': ['Вы не прикрепили файлы'],
                    },
                    {
                        'client_org': ['Вы не прикрепили файлы'],
                    }
                ]
            )

        return cleaned_data


class FilterForm(forms.Form):
    search = forms.CharField(max_length=256)

app/api/views.py
from django.shortcuts import render
from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework.status import HTTP_200_OK
from rest_framework.decorators import api_view
from django.db.models import Q

from clients.utils import update
from clients.models import Client, Organization, Bill
from api.serializers import (
    UploadFilesSerializer,
    ClientModelSerializer,
    OrganizationModelSerializer,
    BillModelSerializer
)


def index(request):
    return render(request, 'api_index.html')


@api_view(['POST'])
def upload_files(request):
    serializer = UploadFilesSerializer(request.POST, request.FILES)
    serializer.is_valid(raise_exception=True)
    bills = request.FILES.get('bills')
    client_org = request.FILES.get('client_org')
    result = update(client_org.file if client_org else None, bills.file if bills else None)
    return Response(result, status=HTTP_200_OK)


class ClientViewSet(viewsets.ModelViewSet):

    serializer_class = ClientModelSerializer
    queryset = Client.objects.all()


class OrganizationViewSet(viewsets.ModelViewSet):

    serializer_class = OrganizationModelSerializer

    def get_queryset(self):
        queryset = Organization.objects.all().prefetch_related('client')
        if 'search' in self.request.query_params:
            search_name = self.request.query_params.get('search')
            queryset = queryset.filter(Q(name__icontains=search_name) | Q(client__name__icontains=search_name))
        return queryset


class BillViewSet(viewsets.ModelViewSet):

    serializer_class = BillModelSerializer

    def get_queryset(self):
        queryset = Bill.objects.all().prefetch_related('organization')
        if 'search' in self.request.query_params:
            search_name = self.request.query_params.get('search')
            queryset = queryset.filter(
                Q(organization__name__icontains=search_name) |
                Q(organization__client__name__icontains=search_name)
            )
        return queryset

app/clients/views.py
from django.views import generic
from django.shortcuts import render, get_object_or_404
from django.db.models import Sum, Q

from clients.utils import update
from clients.forms import UploadForm, FilterForm
from clients.models import Client, Bill, Organization


def index(request):
    return render(request, 'client_index.html')


class BillsView(generic.list.ListView):
    model = Bill
    template_name = 'bill_list.html'

    def get_queryset(self):
        queryset = Bill.objects.all()
        search_name = self.request.GET.get('search')
        if search_name is not None:
            queryset = queryset.filter(
                Q(organization__name__icontains=search_name) |
                Q(organization__client__name__icontains=search_name)
            )
        return queryset

    def render_to_response(self, context, **response_kwargs):
        context['filter_form'] = FilterForm()
        return super(BillsView, self).render_to_response(context, **response_kwargs)


class ClientView(generic.list.ListView):
    model = Client
    template_name = 'client_list.html'


class OrganizationView(generic.list.ListView):
    model = Organization
    template_name = 'organization_list.html'

    def get_queryset(self):
        queryset = Organization.objects.all()
        search_name = self.request.GET.get('search')
        if search_name is not None:
            queryset = queryset.filter(Q(name__icontains=search_name) | Q(client__name__icontains=search_name))
        return queryset

    def render_to_response(self, context, **response_kwargs):
        context['filter_form'] = FilterForm()
        return super(OrganizationView, self).render_to_response(context, **response_kwargs)


class ClientDetailViews(generic.detail.DetailView):
    model = Client
    template_name = 'client_detail.html'
    slug_field = 'name'

    def get_object(self, queryset=None):
        slug = self.kwargs.get(self.slug_url_kwarg, None)
        obj = get_object_or_404(Client, name=slug)
        return obj

    def get_context_data(self, **kwargs):
        context = super(ClientDetailViews, self).get_context_data(**kwargs)
        bills_sum = Bill.objects.filter(organization__client=self.object).aggregate(Sum('sum')).get('sum__sum')
        organizations_count = Organization.objects.filter(client=self.object).count()
        context['bills_sum'] = bills_sum if bills_sum is not None else 0
        context['organizations_count'] = organizations_count
        return context


def upload_files(request):
    errors = []
    success = False
    if request.method == 'POST':
        files = UploadForm(request.POST, request.FILES)
        if files.is_valid():
            bills = request.FILES.get('bills')
            client_org = request.FILES.get('client_org')
            update(client_org.file if client_org else None, bills.file if bills else None)
            success = True
        else:
            errors = files.errors

    form = UploadForm()
    return render(request, 'upload_files.html',
                  {'form': form, 'errors': errors, 'success': success})
    

app/src/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'index.html')

app/api/templates/api_index.html
{% extends 'base.html' %}


{% block title %}API{% endblock %}


{% block body %}
    <h1>API</h1>
    <ul>Эндпоинты:<br><br>
    <li><a href="{% url 'api:upload_files' %}">Загрузка файлов</a></li>
    bills: data: файл формата xls или xlsx <br>
    client_org: data: файл формата xls или xlsx<br><br>
    <li><a href="/api/clients/">Клиенты</a></li><br>
    <li><a href="/api/organizations/">Организации</a></li>
    search: query parameter: имя клиента или организации<br><br>
    <li><a href="/api/bills/">Счета</a></li>
    search: query parameter: имя клиента или организации<br>
    </ul>
{% endblock %}

app/clients/templates/bill_list.html
{% extends 'client_base.html' %}

{% block title %}Bills{% endblock %}

{% block body %}

    <h1>Счета организаций:</h1>

    <form method="GET" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ filter_form.as_p }}
        <button type="submit" class="save btn btn-default">Поиск</button>
    </form>

    {% if object_list %}

        <table border="1">
        <caption>Bills</caption>
       <tr>
        <th>id</th>
        <th>Организация</th>
        <th>№</th>
        <th>Сумма</th>
        <th>Дата</th>
       </tr>

        {% for bill in object_list %}
            <tr>
                <td>{{ bill.id }}</td><td>{{ bill.organization.name }}</td>
                <td>{{ bill.unique_id }}</td><td>{{ bill.sum }}</td><td>{{ bill.date }}</td>
            </tr>
        {% endfor %}

        </table>

    {% else %}
        <h2>Организаций пока что нет.</h2>
    {% endif %}

{% endblock %}

app/clients/templates/client_base.html
{% extends 'base.html' %}


{% block project_urls %}
    <li><a href="{% url 'clients:upload_files' %}">Загрузка файлов</a></li>
    <li><a href="{% url 'clients:clients_list' %}">Клиенты</a></li>
    <li><a href="{% url 'clients:organizations_list' %}">Организации</a></li>
    <li><a href="{% url 'clients:bills_list' %}">Счета</a></li>
{% endblock %}

app/clients/templates/client_detail.html
{% extends 'client_base.html' %}

{% block title %}Client {{ object.name }}{% endblock %}

{% block body %}

    {% if object %}

    <h1>Клиент {{ object.name }}:</h1>

        <table border="1">
        <caption>Client</caption>
       <tr>
        <th>id</th>
        <th>Имя</th>
        <th>Кол-во организаций</th>
        <th>Сумма по счетам организаций</th>
       </tr>
        <tr>
            <td>{{ object.id }}</td><td>{{ object.name }}</td>
            <td>{{ organizations_count }}</td><td>{{ bills_sum }}</td>
       </tr>
        </table>

    {% else %}
        <h2>Такого клиента не существует</h2>
    {% endif %}

{% endblock %}

app/clients/templates/client_index.html
{% extends 'client_base.html' %}


{% block title %}Главная: Клиенты{% endblock %}


{% block body %}
    <h1>Клиенты</h1>
    Это главная страница клиенты
{% endblock %}

app/clients/templates/client_list.html
{% extends 'client_base.html' %}

{% block title %}Clients{% endblock %}

{% block body %}

    <h1>Клиенты:</h1>

    {% if object_list %}

        <table border="1">
        <caption>Clients</caption>
       <tr>
        <th>id</th>
        <th>Имя</th>
       </tr>

        {% for cli in object_list %}
            <tr>
                <td><a href="{% url "clients:clients_detailed" slug=cli.name %}">{{ cli.id }}</a></td>
                <td>{{ cli.name }}</td>
            </tr>
        {% endfor %}

        </table>

    {% else %}
        <h2>Клиентов пока что нет.</h2>
    {% endif %}

{% endblock %}

app/clients/templates/organization_list.html
{% extends 'client_base.html' %}

{% block title %}Organizations{% endblock %}

{% block body %}

    <h1>Организации:</h1>

    <form method="GET" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ filter_form.as_p }}
        <button type="submit" class="save btn btn-default">Поиск</button>
    </form>

    {% if object_list %}

        <table border="1">
        <caption>Organizations</caption>
       <tr>
        <th>id</th>
        <th>Имя</th>
        <th>Клиент</th>
       </tr>

        {% for org in object_list %}
            <tr><td>{{ org.id }}</td><td>{{ org.name }}</td><td>{{ org.client.name }}</td></tr>
        {% endfor %}

        </table>

    {% else %}
        <h2>Организаций пока что нет.</h2>
    {% endif %}

{% endblock %}

app/clients/templates/upload_files.html
{% extends 'client_base.html' %}

{% block title %}Upload{% endblock %}

{% block body %}
    <h1>Загрузка файлов</h1>
<form method="POST" class="post-form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Загрузить</button>
</form>
{% if success %}
    <h2>Успешно</h2>
{% endif %}
{% if errors %}
    <h2>Ошибки</h2>
    {{ errors }}
{% endif %}
{% endblock %}

app/src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<ul>
    <li><a href="{% url 'main' %}">Главная</a></li>
    {% block project_urls %}
        <li><a href="{% url 'clients:main' %}">Клиенты</a></li>
        <li><a href="{% url 'api:main' %}">API</a></li>
    {% endblock %}
</ul>
{% block body %}
{% endblock %}
</body>
</html>

app/src/templates/index.html
{% extends 'base.html' %}


{% block title %}Главная{% endblock %}


{% block body %}
    <h1>Главная</h1>
    Это главная страница тестового задания, выше представлены ссылки на страницы
{% endblock %}